"""Origin-aware TOML inputs and bounded script companion discovery."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from copy import deepcopy
from dataclasses import dataclass
import os
from pathlib import Path
import subprocess
import tomllib
from typing import cast

import tomlkit

from .layout import AgentLayout

PROJECTION_HEADER = (
    "# Generated by Toolang; edit the authored toolang.toml files instead.\n"
)
PROJECTION_KEY = "__toolang_sources__"


@dataclass(frozen=True, slots=True)
class ConfigSource:
    path: Path
    config: dict[str, object]


def read_config(path: Path) -> dict[str, object]:
    """Read one optional TOML file, preserving its discovered path as origin."""
    if not path.exists() and not path.is_symlink():
        return {}
    try:
        return rebase_config(
            tomllib.loads(path.read_text(encoding="utf-8")), path.parent
        )
    except (OSError, ValueError) as exc:
        raise ValueError(f"could not read configuration {path}: {exc}") from exc


def rebase_config(config: Mapping[str, object], directory: Path) -> dict[str, object]:
    """Resolve known host paths; plugin commands and guest paths remain opaque."""
    result = deepcopy(dict(config))
    workspaces = result.get("workspaces")
    if isinstance(workspaces, dict):
        workspaces = cast(dict[str, object], workspaces)
        for name, path in workspaces.items():
            if isinstance(path, str) and path:
                workspaces[name] = str(resolve_path(path, directory))
    catalog = catalog_config(result)
    if catalog is not None and isinstance(catalog.get("path"), str):
        catalog["path"] = str(resolve_path(str(catalog["path"]), directory))
    return result


def rebase_config_content(content: bytes, directory: Path) -> bytes:
    """Bind relative paths into captured bytes without changing unrelated files."""
    parsed = tomllib.loads(content.decode("utf-8"))
    resolved = rebase_config(parsed, directory)
    return content if parsed == resolved else tomlkit.dumps(resolved).encode("utf-8")


def resolve_path(value: str, directory: Path) -> Path:
    path = Path(value).expanduser()
    return (path if path.is_absolute() else directory / path).resolve()


def catalog_config(config: Mapping[str, object]) -> dict[str, object] | None:
    value: object = config
    for key in ("plugin", "model_catalog", "models_dev"):
        value = value.get(key) if isinstance(value, dict) else None
    return cast(dict[str, object], value) if isinstance(value, dict) else None


def script_directories(source: Path) -> tuple[Path, ...]:
    """Return source-first directories through the nearest Git worktree boundary."""
    srcdir = source.resolve(strict=True).parent
    for directory in (srcdir, *srcdir.parents):
        marker = directory / ".git"
        if not marker.exists() and not marker.is_symlink():
            continue
        environ = {
            key: value
            for key, value in os.environ.items()
            if not key.startswith("GIT_")
        }
        result = subprocess.run(
            ["git", "-C", str(directory), "rev-parse", "--show-toplevel"],
            env=environ,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode or Path(result.stdout.strip()).resolve() != directory:
            raise ValueError(f"invalid Git worktree boundary: {marker}")
        return tuple(
            parent
            for parent in (srcdir, *srcdir.parents)
            if parent == directory or parent.is_relative_to(directory)
        )
    return (srcdir,)


def script_sources(source: Path) -> tuple[ConfigSource, ...]:
    """Capture outer-to-inner layers without inheriting ancestor workspace grants."""
    directories = script_directories(source)
    sources: list[ConfigSource] = []
    for directory in reversed(directories):
        path = directory / "toolang.toml"
        companion = directory / "toolang.catalog.json"
        if not any(item.exists() or item.is_symlink() for item in (path, companion)):
            continue
        config = read_config(path)
        if directory != directories[0]:
            config.pop("workspaces", None)
        # Catalog-only layers retain their position without requiring TOML.
        sources.append(ConfigSource(path, config))
    return tuple(sources)


def config_sources(
    layout: AgentLayout, *, include_agent: bool = True
) -> tuple[ConfigSource, ...]:
    """Load normal root/home layers or captured roaming project layers."""
    if layout.placement == "roaming":
        config = read_config(layout.config)
        raw = config.get(PROJECTION_KEY)
        if isinstance(raw, list):
            return tuple(
                ConfigSource(
                    Path(str(item["path"])), cast(dict[str, object], item["config"])
                )
                for item in cast(list[dict[str, object]], raw)
            )
        return (ConfigSource(layout.config, config),)
    paths = (layout.root_config, *((layout.config,) if include_agent else ()))
    return tuple(ConfigSource(path, read_config(path)) for path in paths)


def merge_mappings(layers: Sequence[Mapping[str, object]]) -> dict[str, object]:
    """Merge mapping fields for inspection and State, not Setup policy resolution."""
    result: dict[str, object] = {}
    for layer in layers:
        for key, value in layer.items():
            previous = result.get(key)
            result[key] = (
                merge_mappings(
                    (cast(dict[str, object], previous), cast(dict[str, object], value))
                )
                if isinstance(previous, dict) and isinstance(value, dict)
                else deepcopy(value)
            )
    return result


def project_sources(
    sources: Sequence[ConfigSource], *, source: Path, catalog: Path | None = None
) -> str:
    """Keep the original ordered layers alongside the State-facing projection."""
    config = merge_mappings([item.config for item in sources])
    config[PROJECTION_KEY] = [
        {"path": str(item.path), "config": item.config} for item in sources
    ]
    config["__toolang_source__"] = str(source)
    if catalog is not None:
        config["__toolang_catalog__"] = str(catalog)
    return PROJECTION_HEADER + tomlkit.dumps(config)


def source_catalog(
    sources: Sequence[ConfigSource], *, roaming: bool, validate: bool = True
) -> Path | None:
    """Pick the nearest authored path or companion without merging catalogs."""
    for source in reversed(sources):
        config = catalog_config(source.config)
        if config is not None and "path" in config:
            path = config["path"]
            if not isinstance(path, str) or not path:
                raise ValueError(f"model catalog path must be nonempty: {source.path}")
            selected = Path(path)
        else:
            selected = source.path.with_name(
                "toolang.catalog.json" if roaming else "catalog.json"
            )
            if not selected.exists() and not selected.is_symlink():
                continue
        if validate and not selected.is_file():
            raise ValueError(f"model catalog is not a file: {selected}")
        return selected
    return None
